spring:
  application:
    name: interfaces
  datasource:
    url: jdbc:postgresql://edatamate.dallas98.top/edatamate
    username: edatamate
    password: edatamate@123
    driver-class-name: org.postgresql.Driver