datamate:
  datamanagement:
    file-storage:
      upload-dir: ${FILE_UPLOAD_DIR:./uploads}
      max-file-size: 10485760   # 10MB
      max-request-size: 52428800 # 50MB
    cache:
      ttl: 3600
      max-size: 1000
# MyBatis is configured centrally in main-application (mapper-locations & aliases)
# to avoid list overriding issues when importing multiple module configs.
