server:
  port: 8092

spring:
  application:
    name: data-management-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/data_engine_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 2000ms
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# 数据管理服务配置
datamanagement:
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-file-size: 10485760  # 10MB
    max-request-size: 52428800  # 50MB
  cache:
    ttl: 3600  # 1 hour
    max-size: 1000

# OpenAPI 文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
# 日志配置
logging:
  level:
    com.dataengine: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/data-management-service.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
