services:
  # 1) backend
  backend:
    container_name: backend
    image: backend
    ports:
      - "8080:8080"
    volumes:
      - ${DATASET_VOLUME}:/dataset
      - ${FLOW_VOLUME}:/flow
      - ${LOG_VOLUME}:/var/log/data-platform
    networks: [ edatamate ]

  # 2) frontend（NodePort 30000）
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - "30000:80"            # nodePort → hostPort
    volumes:
      - ${LOG_VOLUME}:/var/log/data-platform
    networks: [ edatamate ]

  # 3) mysql
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Huawei@123
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      - ../../../scripts/db:/docker-entrypoint-initdb.d
      - ${LOG_VOLUME}:/var/log/data-platform
    networks: [ edatamate ]

networks:
  edatamate:
    driver: bridge
