services:
  # 1) backend
  backend:
    container_name: backend
    image: backend
    ports:
      - "8080:8080"
    volumes:
      - ${BASE_VOLUME}${DATASET_VOLUME}:/dataset
      - ${BASE_VOLUME}${FLOW_VOLUME}:/flow
      - ${BASE_VOLUME}${LOG_VOLUME}:/var/log/data-platform
    networks: [ edatamate ]

  # 2) frontend（NodePort 30000）
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - "30000:80"            # nodePort → hostPort
    volumes:
      - ${BASE_VOLUME}${LOG_VOLUME}:/var/log/data-platform
    networks: [ edatamate ]

  # 3) mysql
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Huawei@123
    ports:
      - "3306:3306"
    volumes:
      - ${BASE_VOLUME}${MYSQL_VOLUME}:/var/lib/mysql
      - ../../../scripts/db:/docker-entrypoint-initdb.d
      - ${BASE_VOLUME}${LOG_VOLUME}:/var/log/data-platform
    networks: [ edatamate ]

  runtime:
    container_name: runtime
    image: runtime
    environment:
      RAY_DEDUP_LOGS: "0"
      RAY_TQDM_PATCH_PRINT: "0"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Huawei@123"
      MYSQL_DATABASE: "dataengine"
    ports:
      - "8081:8081"
    command:
      - python
      - /opt/runtime/data_platform/operator_runtime.py
      - --port
      - "8081"
    volumes:
      - ${BASE_VOLUME}${RAY_LOG_VOLUME}:/tmp/ray
      - ${BASE_VOLUME}${LOG_VOLUME}:/var/log/data-platform
      - ${BASE_VOLUME}${DATASET_VOLUME}:/dataset
      - ${BASE_VOLUME}${FLOW_VOLUME}:/flow

networks:
  edatamate:
    driver: bridge
