apiVersion: apps/v1
kind: Deployment
metadata:
  name: datax
  labels:
    app: datax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datax
  template:
    metadata:
      labels:
        app: datax
    spec:
      containers:
      - name: datax
        image: datax
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
        command:
          - bash
          - -c
          - rpcbind && python3 /opt/datax/bin/app.py
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dataset
          mountPath: /dataset
          subPath: dataset
      volumes:
      - name: dataset
        hostPath:
          path: /tmp/data-mate

---
apiVersion: v1
kind: Service
metadata:
  name: datax
  labels:
    app: datax
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: datax
