datamate:
  data-collection:
    # DataX配置
    datax:
      home-path: ${DATAX_HOME:D:/datax}
      python-path: ${DATAX_PYTHON_PATH:python3}
      job-config-path: ${DATAX_JOB_PATH:./data/temp/datax/jobs}
      log-path: ${DATAX_LOG_PATH:./logs/datax}
      max-memory: ${DATAX_MAX_MEMORY:2048}
      channel-count: ${DATAX_CHANNEL_COUNT:5}

    # 执行配置
    execution:
      max-concurrent-tasks: ${DATA_COLLECTION_MAX_CONCURRENT_TASKS:10}
      task-timeout-minutes: ${DATA_COLLECTION_TASK_TIMEOUT:120}
      retry-count: ${DATA_COLLECTION_RETRY_COUNT:3}
      retry-interval-seconds: ${DATA_COLLECTION_RETRY_INTERVAL:30}

    # 监控配置
    monitoring:
      status-check-interval-seconds: ${DATA_COLLECTION_STATUS_CHECK_INTERVAL:30}
      log-retention-days: ${DATA_COLLECTION_LOG_RETENTION:30}
      enable-metrics: ${DATA_COLLECTION_ENABLE_METRICS:true}
