name: Backend Docker Image CI When PR

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'backend/**'
      - 'build/backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'backend/**'
      - 'build/backend/**'
      - '.github/workflows/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make build-backend
